/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.NhanVienDAO;
import helper.DialogHelper;
import helper.GlobalData;
import helper.ShareHelper;
import java.awt.event.KeyEvent;
import model.NhanVien;

/**
 *
 * @author qng_nhat
 */
public class frmLogin extends javax.swing.JFrame {

    NhanVienDAO dao = new NhanVienDAO();
    
    public frmLogin() {
        initComponents();
        setLocationFrame();
        txtPasswordShowText.setVisible(false);
        btnHidePassword.setVisible(false);
    }
    
    private void setLocationFrame(){
        this.setLocationRelativeTo(null);
    }
    
    void login() {
        String username = txtUsername.getText();
        String password = String.valueOf(pwfPassword.getPassword());
        try {
            NhanVien nhanVien = dao.findByName(username);
            if (nhanVien != null) {
                String matKhau2 = nhanVien.getMatKhau();
                if (password.equals(matKhau2)) {
                    ShareHelper.USER=nhanVien;
                    GlobalData.setLoggedMaNhanVien(nhanVien.getMaNV());
                    GlobalData.setLoggedRole(nhanVien.isVaiTro());
                    GlobalData.setLoggedUser("Logged");
                    DialogHelper.alert(this, "Đăng nhập thành công!");
                    this.dispose();
                } else {
                    DialogHelper.alert(this, "Kiểm tra lại mật khẩu!");
                    pwfPassword.setText("");
                    pwfPassword.requestFocus();
                }
            } else {
                DialogHelper.alert(this, "Kiểm tra lại tên đăng nhập!");
                txtUsername.setText("");
                txtUsername.requestFocus();
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        pnlTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        pwfPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnShowPassword = new javax.swing.JLabel();
        txtPasswordShowText = new javax.swing.JTextField();
        btnHidePassword = new javax.swing.JLabel();
        btnSkip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        pnlTop.setBackground(new java.awt.Color(0, 140, 206));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_customer_96px.png"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLogin.setText("login");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogin)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblLogin)
                .addGap(20, 20, 20))
        );

        pnlMain.setBackground(new java.awt.Color(0, 112, 206));
        pnlMain.setLayout(null);

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        lblUserName.setText("username");
        pnlMain.add(lblUserName);
        lblUserName.setBounds(38, 28, 91, 29);

        txtUsername.setBackground(new java.awt.Color(0, 112, 206));
        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        pnlMain.add(txtUsername);
        txtUsername.setBounds(48, 63, 350, 42);
        pnlMain.add(jSeparator1);
        jSeparator1.setBounds(48, 111, 350, 10);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        lblPassword.setText("password");
        pnlMain.add(lblPassword);
        lblPassword.setBounds(38, 127, 87, 29);

        pwfPassword.setBackground(new java.awt.Color(0, 112, 206));
        pwfPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwfPassword.setForeground(new java.awt.Color(204, 204, 204));
        pwfPassword.setBorder(null);
        pwfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfPasswordKeyPressed(evt);
            }
        });
        pnlMain.add(pwfPassword);
        pwfPassword.setBounds(50, 160, 310, 42);
        pnlMain.add(jSeparator2);
        jSeparator2.setBounds(48, 210, 350, 10);

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_enter_32px.png"))); // NOI18N
        btnLogin.setText("login");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        pnlMain.add(btnLogin);
        btnLogin.setBounds(90, 250, 110, 50);
        btnLogin.getAccessibleContext().setAccessibleDescription("");

        btnShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_show_password_32px.png"))); // NOI18N
        btnShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPasswordMouseClicked(evt);
            }
        });
        pnlMain.add(btnShowPassword);
        btnShowPassword.setBounds(370, 170, 32, 32);

        txtPasswordShowText.setBackground(new java.awt.Color(0, 112, 206));
        txtPasswordShowText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPasswordShowText.setForeground(new java.awt.Color(204, 204, 204));
        txtPasswordShowText.setBorder(null);
        txtPasswordShowText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordShowTextActionPerformed(evt);
            }
        });
        txtPasswordShowText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordShowTextKeyPressed(evt);
            }
        });
        pnlMain.add(txtPasswordShowText);
        txtPasswordShowText.setBounds(50, 160, 310, 42);

        btnHidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_show_password_32px.png"))); // NOI18N
        btnHidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHidePasswordMouseClicked(evt);
            }
        });
        pnlMain.add(btnHidePassword);
        btnHidePassword.setBounds(370, 170, 32, 32);

        btnSkip.setBackground(new java.awt.Color(255, 255, 255));
        btnSkip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSkip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_32px.png"))); // NOI18N
        btnSkip.setText("skip");
        btnSkip.setBorder(null);
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });
        btnSkip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSkipKeyPressed(evt);
            }
        });
        pnlMain.add(btnSkip);
        btnSkip.setBounds(240, 250, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (txtUsername.getText().equals("")) {
            DialogHelper.alert(this, "Nhập username!!");
            txtUsername.requestFocus();
        }
        if (pwfPassword.getPassword().equals("")) {
            DialogHelper.alert(this, "Nhập password!!");
            pwfPassword.requestFocus();
        }
        if (pwfPassword.getPassword().length < txtPasswordShowText.getText().length()) {
            pwfPassword.setText(txtPasswordShowText.getText());
        }
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPasswordMouseClicked
        pwfPassword.setVisible(false);
        btnShowPassword.setVisible(false);
        btnHidePassword.setVisible(true);
        txtPasswordShowText.setVisible(true);
        txtPasswordShowText.setText(String.valueOf(pwfPassword.getPassword()));
    }//GEN-LAST:event_btnShowPasswordMouseClicked

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed

    }//GEN-LAST:event_btnLoginKeyPressed

    private void pwfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_pwfPasswordKeyPressed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pwfPassword.requestFocus();
        }
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordShowTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordShowTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordShowTextActionPerformed

    private void txtPasswordShowTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordShowTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_txtPasswordShowTextKeyPressed

    private void btnHidePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHidePasswordMouseClicked
        pwfPassword.setVisible(true);
        btnShowPassword.setVisible(true);
        btnHidePassword.setVisible(false);
        txtPasswordShowText.setVisible(false);
        pwfPassword.setText(txtPasswordShowText.getText());
    }//GEN-LAST:event_btnHidePasswordMouseClicked

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        this.dispose();
        new frmMain().setVisible(true);
    }//GEN-LAST:event_btnSkipActionPerformed

    private void btnSkipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSkipKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSkipKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHidePassword;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnShowPassword;
    private javax.swing.JButton btnSkip;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JTextField txtPasswordShowText;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
